#!/bin/sh

export VNC_PORT

VNC_PORT='5800'


find_interfaces() {
    ip a | grep -E '^[0-9]*: .*' | cut -d ' ' -f '2' | grep -o '[^:]*' | grep -v 'lo' | grep -v 'docker.*'
}

lookup_windows_machines() {
    nmblookup --option=interfaces="${1}" -S "${2}" | grep -oE '^([0-9]{1,3}.){3}[0-9]{1,3}'
}

check_vnc_port() {
    nc -zvw3 "${1}" "${VNC_PORT}" 2> /dev/null
}

print_vnc_hosts() {
    for ip_address in "$@" ; do
        check_vnc_port "${ip_address}" && echo -n "${ip_address} "
    done
}

for interface in $(find_interfaces) ; do
    print_vnc_hosts $(lookup_windows_machines "${interface}" "${1}")
done
